const STORAGE_KEY='finance-wesleyana-v1';
const categories={expense:['Alimentação','Transporte','Casa','Assinaturas','Lazer','Saúde','Compras','Cartão','Outros'],income:['Salário','Freela','Reembolso','Venda','Presente','Outros'],reserve:['Reserva','Investimento','Meta']};
const icons={'Alimentação':'🍽️','Transporte':'🚗','Casa':'🏠','Assinaturas':'📺','Lazer':'🎮','Saúde':'🩺','Compras':'🛍️','Cartão':'💳','Salário':'💼','Freela':'🧰','Reembolso':'↩️','Venda':'🏷️','Presente':'🎁','Reserva':'🛡️','Investimento':'📈','Meta':'🎯','Outros':'•'};
const defaultState={scope:'sidmar',filter:'all',balances:{sidmar:0,ana:0,joint:0},transactions:[],goals:[]};
let state=loadState();
let currentType='expense';
function loadState(){try{return {...defaultState,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return structuredClone(defaultState)}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const brl=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(n)||0);
const parseMoney=v=>Number(String(v||'0').replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''))||0;
const today=()=>new Date().toISOString().slice(0,10);
const ownerLabel=o=>o==='sidmar'?'Wesley':o==='ana'?'Ana':'Nós';
function inScope(item){if(state.scope==='joint') return item.owner==='joint'||item.owner==='sidmar'||item.owner==='ana';return item.owner===state.scope}
function thisMonth(date){const d=new Date(date+'T12:00:00'),n=new Date();return d.getMonth()===n.getMonth()&&d.getFullYear()===n.getFullYear()}
function setMonth(){ $('#monthLabel').textContent=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date()).toUpperCase() }
function getVisible(){return state.transactions.filter(t=>inScope(t)&&thisMonth(t.date))}
function render(){setMonth();renderScope();renderMetrics();renderTransactions();renderCategories();renderGoals();renderFuture();renderInsight();}
function renderScope(){document.body.dataset.theme=state.scope==='sidmar'?'wesley':state.scope==='ana'?'ana':'joint';const themeColors={wesley:'#06142f',ana:'#2a1020',joint:'#171026'};document.querySelector('meta[name="theme-color"]').setAttribute('content',themeColors[document.body.dataset.theme]);$$('.scope-btn').forEach(b=>b.classList.toggle('active',b.dataset.scope===state.scope));$('#scopeTitle').textContent=state.scope==='sidmar'?'Finanças de Wesley':state.scope==='ana'?'Finanças de Ana':'Nossa visão financeira';const visible=getVisible();const income=sum(visible.filter(t=>t.type==='income'&&t.status==='paid'));const expense=sum(visible.filter(t=>t.type==='expense'&&t.status==='paid'));const pending=sum(visible.filter(t=>t.type==='expense'&&t.status==='pending'));const reserve=sum(visible.filter(t=>t.type==='reserve'&&t.status==='paid'));let balance=state.scope==='joint'?state.balances.sidmar+state.balances.ana+state.balances.joint:state.balances[state.scope];const free=Math.max(balance-pending-reserve,0);$('#currentBalance').textContent=brl(balance);$('#committedMoney').textContent=brl(pending);$('#savedMoney').textContent=brl(reserve);$('#freeMoney').textContent=brl(free);const ratio=balance>0?Math.min(100,(free/balance)*100):0;$('#availableTrack').style.width=ratio+'%';const delta=income?((income-expense)/income)*100:0;const el=$('#monthlyDelta');el.textContent=(delta>=0?'+':'')+delta.toFixed(0)+'% no mês';el.className='delta '+(delta<0?'negative':delta>0?'positive':'neutral')}
function sum(arr){return arr.reduce((a,t)=>a+Number(t.amount||0),0)}
function renderMetrics(){const v=getVisible();const incomes=v.filter(t=>t.type==='income'&&t.status==='paid');const expenses=v.filter(t=>t.type==='expense'&&t.status==='paid');const reserves=v.filter(t=>t.type==='reserve'&&t.status==='paid');const recurring=v.filter(t=>t.recurring&&t.type==='expense');$('#incomeTotal').textContent=brl(sum(incomes));$('#expenseTotal').textContent=brl(sum(expenses));$('#reserveTotal').textContent=brl(sum(reserves));$('#recurringTotal').textContent=brl(sum(recurring));$('#incomeCount').textContent=`${incomes.length} lançamento${incomes.length===1?'':'s'}`;$('#expenseCount').textContent=`${expenses.length} lançamento${expenses.length===1?'':'s'}`;$('#recurringCount').textContent=`${recurring.length} recorrente${recurring.length===1?'':'s'}`}
function renderTransactions(){let v=getVisible().sort((a,b)=>b.date.localeCompare(a.date));if(state.filter!=='all')v=v.filter(t=>t.type===state.filter);const box=$('#transactionList');if(!v.length){box.innerHTML='<div class="empty-state">Nenhum lançamento nesta visão ainda.</div>';return}box.innerHTML=v.slice(0,20).map(t=>`<div class="transaction-item"><div class="tx-icon">${icons[t.category]||'•'}</div><div><h4>${escapeHtml(t.description)}</h4><p>${t.category} · ${ownerLabel(t.owner)}${t.account?' · '+escapeHtml(t.account):''} · ${new Intl.DateTimeFormat('pt-BR').format(new Date(t.date+'T12:00:00'))}${t.status==='pending'?' · pendente':''}</p></div><div class="transaction-amount ${t.type}">${t.type==='expense'?'-':t.type==='income'?'+':''}${brl(t.amount)}</div></div>`).join('')}
function renderCategories(){const ex=getVisible().filter(t=>t.type==='expense'&&t.status==='paid');const grouped={};ex.forEach(t=>grouped[t.category]=(grouped[t.category]||0)+t.amount);const entries=Object.entries(grouped).sort((a,b)=>b[1]-a[1]);const total=sum(ex),box=$('#categoryChart');if(!entries.length){box.innerHTML='<div class="empty-state">Os gastos por categoria aparecerão aqui.</div>';return}box.innerHTML=entries.slice(0,6).map(([name,val])=>`<div><div class="category-row-header"><span>${icons[name]||'•'} ${name}</span><strong>${brl(val)}</strong></div><div class="category-bar"><div class="category-fill" style="width:${Math.round(val/total*100)}%"></div></div></div>`).join('')}
function renderGoals(){const gs=state.goals.filter(g=>state.scope==='joint'||g.owner===state.scope||g.owner==='joint');const box=$('#goalList');if(!gs.length){box.innerHTML='<div class="empty-state">Crie uma meta para acompanhar reservas e objetivos.</div>';return}box.innerHTML=gs.map(g=>{const pct=g.target?Math.min(100,g.current/g.target*100):0;return `<div class="goal-card"><div class="goal-top"><strong>${escapeHtml(g.name)}</strong><span>${Math.round(pct)}%</span></div><div class="goal-bar"><div class="goal-fill" style="width:${pct}%"></div></div><small>${brl(g.current)} de ${brl(g.target)} · ${ownerLabel(g.owner)}</small></div>`}).join('')}
function renderFuture(){const upcoming=state.transactions.filter(t=>inScope(t)&&t.type==='expense'&&(t.status==='pending'||t.recurring)).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,5);const box=$('#futureList');if(!upcoming.length){box.innerHTML='<div class="empty-state">Compromissos futuros e recorrências aparecerão aqui.</div>';return}box.innerHTML=upcoming.map(t=>`<div class="future-item"><div><strong>${escapeHtml(t.description)}</strong><span>${t.recurring?'Recorrente · ':''}${ownerLabel(t.owner)}</span></div><strong>${brl(t.amount)}</strong></div>`).join('')}
function renderInsight(){const v=getVisible();const income=sum(v.filter(t=>t.type==='income'&&t.status==='paid')),expense=sum(v.filter(t=>t.type==='expense'&&t.status==='paid'));if(!v.length){$('#insightTitle').textContent='Comece registrando seus movimentos.';$('#insightText').textContent='A Finance Wesleyana transforma seus lançamentos em uma visão simples do que entrou, saiu e ainda pode ser usado.';return}if(income>0){const rate=(expense/income)*100;$('#insightTitle').textContent=rate<=60?'Seu mês está respirando bem.':rate<=90?'Atenção ao ritmo de gastos.':'Seus gastos já passaram da sua renda.';$('#insightText').textContent=`Até agora, ${Math.round(rate)}% das entradas registradas foram consumidas por despesas pagas.`}else{$('#insightTitle').textContent='Você já está mapeando seus gastos.';$('#insightText').textContent=`Há ${v.length} movimentações registradas nesta visão. Adicione receitas para comparar entradas e saídas.`}}
function fillCategories(type){const sel=$('#txCategory');sel.innerHTML=categories[type].map(c=>`<option>${c}</option>`).join('')}
function openTx(prefill={}){currentType=prefill.type||'expense';$$('.segment').forEach(b=>b.classList.toggle('active',b.dataset.type===currentType));fillCategories(currentType);$('#txAmount').value=prefill.amount?String(prefill.amount).replace('.',','):'';$('#txDescription').value=prefill.description||'';if(prefill.category&&categories[currentType].includes(prefill.category))$('#txCategory').value=prefill.category;$('#txOwner').value=prefill.owner||(state.scope==='joint'?'joint':state.scope);$('#txAccount').value=prefill.account||'';$('#txDate').value=prefill.date||today();$('#txStatus').value=prefill.status||'paid';$('#txRecurring').checked=!!prefill.recurring;$('#transactionDialog').showModal()}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function parseQuick(text){const raw=text.trim();if(!raw)return null;const lower=raw.toLowerCase();let type=/(recebi|ganhei|entrou|salário|salario)/.test(lower)?'income':/(guardei|reservei|investi)/.test(lower)?'reserve':'expense';const m=raw.match(/(?:r\$\s*)?(\d+(?:[.,]\d{1,2})?)/i);const amount=m?parseMoney(m[1]):0;let category='Outros';const rules=[['gasolina|combustível|combustivel|uber|ônibus|onibus','Transporte'],['netflix|crunchyroll|spotify|prime|assinatura','Assinaturas'],['mercado|restaurante|lanche|comida|ifood','Alimentação'],['remédio|remedio|farmácia|farmacia|consulta','Saúde'],['salário|salario','Salário'],['freela|freelance','Freela'],['guardei|reservei','Reserva'],['investi|investimento','Investimento']];for(const [re,c] of rules)if(new RegExp(re,'i').test(raw)){category=c;break}if(!categories[type].includes(category))category=categories[type][0];let owner=state.scope==='joint'?'joint':state.scope;let account='';for(const a of ['Nubank','Mercado Pago','Banco do Brasil','BB','Pix','Dinheiro'])if(lower.includes(a.toLowerCase())){account=a;break}let description=category;const known=['gasolina','netflix','crunchyroll','spotify','mercado','restaurante','salário','salario','freela'];const k=known.find(x=>lower.includes(x));if(k)description=k.charAt(0).toUpperCase()+k.slice(1);return {type,amount,category,owner,account,description,date:today(),status:'paid'}}
$$('.scope-btn').forEach(b=>b.onclick=()=>{state.scope=b.dataset.scope;saveState();render()});
$$('.filter-btn').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;$$('.filter-btn').forEach(x=>x.classList.toggle('active',x===b));renderTransactions()});
$('#openQuickAddBtn').onclick=()=>openTx();
$('#transactionForm').onsubmit=e=>{e.preventDefault();const tx={id:crypto.randomUUID(),type:currentType,amount:parseMoney($('#txAmount').value),description:$('#txDescription').value.trim(),category:$('#txCategory').value,owner:$('#txOwner').value,account:$('#txAccount').value.trim(),date:$('#txDate').value,status:$('#txStatus').value,recurring:$('#txRecurring').checked,createdAt:Date.now()};if(!tx.amount||!tx.description)return toast('Informe valor e descrição.');state.transactions.push(tx);saveState();$('#transactionDialog').close();render();toast('Lançamento salvo.')};
$$('.segment').forEach(b=>b.onclick=()=>{currentType=b.dataset.type;$$('.segment').forEach(x=>x.classList.toggle('active',x===b));fillCategories(currentType)});
$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
$('#openGoalBtn').onclick=()=>$('#goalDialog').showModal();
$('#goalForm').onsubmit=e=>{e.preventDefault();state.goals.push({id:crypto.randomUUID(),name:$('#goalName').value.trim(),target:parseMoney($('#goalTarget').value),current:parseMoney($('#goalCurrent').value),owner:$('#goalOwner').value,deadline:$('#goalDeadline').value});saveState();$('#goalDialog').close();e.target.reset();render();toast('Meta criada.')};
$('#openSettingsBtn').onclick=()=>{$('#balanceSidmar').value=String(state.balances.sidmar||'').replace('.',',');$('#balanceAna').value=String(state.balances.ana||'').replace('.',',');$('#balanceJoint').value=String(state.balances.joint||'').replace('.',',');$('#settingsDialog').showModal()};
$('#settingsForm').onsubmit=e=>{e.preventDefault();state.balances={sidmar:parseMoney($('#balanceSidmar').value),ana:parseMoney($('#balanceAna').value),joint:parseMoney($('#balanceJoint').value)};saveState();$('#settingsDialog').close();render();toast('Saldos atualizados.')};
$('#interpretBtn').onclick=()=>{const p=parseQuick($('#quickText').value);const box=$('#interpretPreview');if(!p||!p.amount){box.classList.remove('hidden');box.innerHTML='<strong>Não consegui identificar o valor.</strong><p class="helper-copy">Tente algo como “gastei 80 de gasolina no Nubank”.</p>';return}box.classList.remove('hidden');box.innerHTML=`<strong>${p.type==='expense'?'Despesa':p.type==='income'?'Receita':'Reserva'} de ${brl(p.amount)}</strong><p class="helper-copy">${p.description} · ${p.category}${p.account?' · '+p.account:''} · ${ownerLabel(p.owner)}</p><button id="confirmInterpret" class="primary-btn compact">Confirmar e revisar</button>`;$('#confirmInterpret').onclick=()=>openTx(p)};
fillCategories('expense');render();
